### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by Lautenschlager-id** [squeek502/heroku-buildpack-luvit#1]
Hello. I'm having some troubles to connect the script to heroku. May you help me?

I'm not sure how to put the lua files and stuff, how to use the cedar-14 + this buildpack at once... it's confusing X_X

**Comment by squeek502** [comment]
Cedar-14 is probably not necessary anymore, that was from when cedar-14 was newer than the default. Heroku-16 probably works (will test that in a bit).

EDIT: Confirmed that this buildpack works fine with Heroku-16, removed that note from the readme.

For general information about installing buildpacks, see: https://devcenter.heroku.com/articles/buildpacks#using-a-third-party-buildpack

For general information about managing files, see: https://devcenter.heroku.com/categories/deployment

**Comment by Lautenschlager-id** [comment]
Thanks for answering!

I got this error:

```
C:\Users\Lautenschlager\Desktop\TranslatorBot>git push heroku master
Counting objects: 50, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (44/44), done.
Writing objects: 100% (50/50), 1.54 MiB | 50.00 KiB/s, done.
Total 50 (delta 24), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://github.com/squeek502/h
eroku-buildpack-luvit.git
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detec
tion-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to translators-bot.
remote:
To https://git.heroku.com/translators-bot.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/translators-bot.git'
```

"App not compatible with buildpack". I'm not sure how to fix it. This is my first time using heroku.

**Comment by squeek502** [comment]
You need to have a [`package.lua`](https://github.com/luvit/lit/wiki/Package-Metadata). An example can be found here: https://github.com/squeek502/heroku-buildpack-luvit/blob/master/examples/luvit_app/package.lua

**Comment by Lautenschlager-id** [comment]
![image](https://user-images.githubusercontent.com/26045253/40204054-99825d72-59fd-11e8-8ec0-78b8fbe96414.png)

This is my repo. It has the `package.lua` (i even tried it inside .git) but the error is the same :(

**Comment by squeek502** [comment]
Make sure `package.lua` is included in the git index. What does your `git status` look like?

**Comment by Lautenschlager-id** [comment]
I believe it worked now! I think I was missing something in my Git thing.

It's throwing an error now but it's a problem in the script as it has some libs to add now.

If I have a problem with this buildpack, I'll open another issue.

Thank you so much! :)
